fix format ci job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,7 +55,7 @@ jobs:
           submodules: 'true'
           fetch-depth: 0
           ref: ${{ github.head_ref }}
-      - name: set pyver for pre-commit cache
+      - name: Set pyver checksum for pre-commit cache
         run: echo "pyver=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
       - name: Cache pre-commit
         uses: actions/cache@v2
@@ -63,8 +63,14 @@ jobs:
           path: ~/.cache/pre-commit
           key: pre-commit-${{ env.pyver }}-${{ hashFiles('.pre-commit-config.yaml') }}
           restore-keys: pre-commit-${{ env.pyver }}-${{ hashFiles('.pre-commit-config.yaml') }}
-      - name: Run pre-commit script
-        run: ./ci/pre-commit.sh
+      - name: Set clang-format version
+        run: |
+          sudo update-alternatives --remove-all clang-format || echo "nothing to remove"
+          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 100
+      - name: Install pre-commit
+        run: pip install pre-commit==2.14.0
+      - name: Run pre-commit
+        run: pre-commit run --all-files || echo "formatting changes required"
       - name: Commit any changes
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
